# Generated by Django 3.2.16 on 2023-01-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomend', '0002_alter_movie_movie_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
