# Generated by Django 4.1.3 on 2023-02-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomend', '0005_questionnaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
