# Generated by Django 4.1.3 on 2023-02-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomend', '0006_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_url', models.URLField(null=True)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
