# Generated by Django 4.1.3 on 2023-02-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomend', '0008_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
