# Generated by Django 4.1.3 on 2023-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomend', '0010_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
